name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download local problems
        id: use-local
        uses: ./
        with:
          local-verify-files-path: tests/verify_files.json
          install: true
          cache-pip: true
          cache: true

      - name: Test local
        run: |
          [ "${{ steps.use-local.outputs.problems }}"  = "http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=ITP1_4_B
          https://judge.yosupo.jp/problem/aplusb
          https://onlinejudge.u-aizu.ac.jp/courses/lesson/2/ITP1/1/ITP1_1_A" ]
          [ "${{ steps.use-local.outputs.problems-hash }}"  = "d54c5839ae3a5164f4b20c28a39a90cf" ]

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: json2
          path: tests/verify_files2.json
          retention-days: 1

      - name: Download artifact problems
        id: use-artifact
        uses: ./
        with:
          verify-files-artifact-name: json2
          verify-files-name: verify_files2.json

      - name: Test artifact
        run: |
          [ "${{ steps.use-artifact.outputs.problems }}"  = "https://onlinejudge.u-aizu.ac.jp/courses/lesson/2/ITP1/1/ITP1_1_A" ]
          [ "${{ steps.use-artifact.outputs.problems-hash }}"  = "1fe359fd6574ab4a8b8ad5a6bb27d373" ]
